# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PORT: 8080
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_ADDRESS: ${{ secrets.PUBLIC_ADDRESS }}
      BLOCKCHAIN_HTTP_URL: ${{ secrets.BLOCKCHAIN_HTTP_URL }}
      PROXY_CONTRACT_ADDRESS: ${{ secrets.PROXY_CONTRACT_ADDRESS }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build --if-present
    - name: Run tests
      run: npm test